# Generated by Django 4.0.1 on 2022-01-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='weight',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
