# Generated by Django 4.0.1 on 2022-01-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss', '0004_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
